title = 'Oh yeah'
published = 2020-08-28T06:37:22Z
episode_fkey = 'saturday-night-live/35x05/index'
show_fkey = 'saturday-night-live/index'
tag = ['bill-hader', 'kristen-wiig', 'hollywood-dish', 'reaction']
body_markdown = """

Bill Hader as Brady Trunk and Kristen Wiig as Anastasia Sticks on Hollywood
Dish during a Taylor Swift interview, nodding and mouthing "oh yeah".

"""

info.colours = '64'
info.filesize = '0.64mb'
info.frames = '38'
info.size = '360Ã—203'
info.time = '2.10 seconds'

[video]
source   = 'youtube'
file     = '7bK5BQVi2ZE'
ext      = 'mp4'
start    = '1:04.9'
duration = '2.1'

[output]
colours  = '64'
fps      = '18'
# loss     = '50'
width    = '360'
