title = 'Poke'
published = 2021-11-20T07:00:00Z
source_fkey = 'galaxy-quest/index'
tag = [
    'jason-nesmith',
    'mathesar',
    'teb',
]
body_markdown = """

Jason pokes Mathesar in the chest. Mathesar makes a soundless squeak.

"""

[video]
source   = 'file'
file     = 'galaxy_quest'
ext      = 'mkv'
start    = '0:08:21.4'
duration = '2.1'
crop     = '960:540'

[output]
colours    = '74'
denoise    = true
dither     = 'bayer:bayer_scale=3'
fps        = '18'
loss       = '20'
max_size   = '1.03mb'
width      = '400'
