title = 'Run in circles'
published = 2021-12-24T15:00:00Z
show_fkey = 'invader-zim/index'
episode_fkey = 'invader-zim/walk-of-doom/index'
tag = [
    'gir',
    'invader-zim',
]
body_markdown = """

Zim, in pain and blinded, runs in circles waving his arms.
Gir chases along gleefully.

"""

info.colours = '64'
info.filesize = '0.23mb'
info.frames = '42'
info.size = '480Ã—270'
info.time = '3.51 seconds'

[video]
source   = 'file'
file     = 'zim_s01e03'
ext      = 'm4v'
start    = '18:09.4'
duration = '3.5'
crop     = '710:400:5:0'

[output]
colours    = '64'
denoise    = true
dither     = 'bayer:bayer_scale=5'
fps        = '12'
loss       = '20'
max_size   = '0.24mb'
