title = 'Kate Bush arms'
published = 2021-06-06T07:00:00Z
source_fkey = 'eurovision/index'
tag = [
    'gjons-tears',
    'tout-lunivers',
    'eurovision-2021',
    'flail',
]
body_markdown = """

Gjon's Tears flails his arms about in a manner reminiscent of Kate Bush,
while performing Tout l'univers.

"""

info.colours = '75'
info.filesize = '1.24mb'
info.frames = '67'
info.size = '400Ã—217'
info.time = '3.73 seconds'

[video]
source   = 'youtube'
file     = 'M_5mo8st8Mc'
ext      = 'mp4'
start    = '2:47.3'
duration = '3.7'
crop     = '1440:780'

[output]
colours    = '74'
denoise    = true
dither     = 'bayer:bayer_scale=2'
fps        = '18'
loss       = '20'
max_size   = '1.25mb'
width      = '400'