title = 'Yuck'
published = 2100-01-01T07:00:00Z
show_fkey = 'ted-lasso/index'
episode_fkey = 'ted-lasso/for-the-children/index'
tag = [
    '404-page-candidate',
    'nathan-shelley',
]
body_markdown = """

Nathan spits back into the glass the mouthful of the drink he’d just taken.

"""

info.colours = '61'
info.filesize = '1.68mb'
info.frames = '72'
info.size = '480×270'
info.time = '3.99 seconds'

[video]
source   = 'file'
file     = 'ted-lasso-104'
ext      = 'm4v'
start    = '13:40.3'
duration = '4'
crop     = '1200:675'

[output]
brightness = '0.04'
colours    = '60'
dither     = 'bayer:bayer_scale=3'
fps        = '18'
loss       = '0'
max_size   = '1.7mb'
