title = 'One-two punch'
published = 2022-03-02T07:00:00Z
show_fkey = 'police-squad/index'
episode_fkey = 'police-squad/testimony-of-evil/index'
tag = [
    'frank-drebin',
    'jerry-layne',
    'lester',
    'tony-diwonderful',
]

body_markdown = """

Frank Drebin, undercover as Tony Diwonderful, punches Lester and Jerry Layne.

"""

info.colours = '75'
info.filesize = '0.88mb'
info.frames = '55'
info.size = '400Ã—250'
info.time = '3.06 seconds'

[video]
source   = 'file'
file     = 'police-squad-106'
ext      = 'm4v'
start    = '15:28.4'
duration = '3'
crop     = '1440:900'

[output]
colours  = '74'
denoise  = true
dither   = 'bayer:bayer_scale=3'
fps      = '18'
loss     = '20'
max_size = '0.9mb'
width    = '400'
