title = 'Human test'
published = 2021-12-13T07:00:00Z
source_fkey = 'ghostbusters/index'
tag = [
    'egon-spengler',
]
body_markdown = """

Egon pokes a hotel guest with his finger to see if he is human.

"""

info.colours = '81'
info.filesize = '3.07mb'
info.frames = '132'
info.size = '400Ã—225'
info.time = '7.34 seconds'

[video]
source   = 'file'
file     = 'ghostbusters'
ext      = 'm4v'
start    = '00:33:26'
duration = '7.3'
crop     = '800:450:140:20'

[output]
colours    = '80'
dither     = 'floyd_steinberg'
loss       = '40'
fps        = '18'
max_size   = '3.1mb'
mode       = 'full'
width      = '400'
