title = 'Welcome Roy'
published = 2100-01-01T07:00:00Z
show_fkey = 'ted-lasso/index'
episode_fkey = 'ted-lasso/do-the-right-est-thing/index'
tag = [
    'jeff-stelling',
    'roy-kent',
    'soccer-saturday',
]
body_markdown = """

Roy turns to look at Jeff Stelling, who shivers.

"""

[video]
source   = 'file'
file     = 'ted_lasso_203'
ext      = 'm4v'
start    = '27:47.5'
duration = '3.2'
crop     = '1200:675'

[output]
colours    = '74'
denoise    = true
dither     = 'bayer:bayer_scale=3'
fps        = '18'
loss       = '20'
max_size   = '0.61mb'
